stages:
  - test
  - build
  - deploy

test project:
  stage: test
  image: node:16
  script:
    - npm install
    - npm test

build project:
  stage: build
  image: node:16
  script:
    - npm install
    - npm run build

deploy project:
  stage: deploy
  image: node:16
  script:
    - sudo snap install --classic heroku
    - heroku create
    - git push heroku main

